# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20180222_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
