# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 17:22
from __future__ import unicode_literals

from django.db import migrations
import userprofile.managers


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('objects', userprofile.managers.ProfileManager()),
            ],
        ),
    ]
